## .rest files require rest client vscode extension
## you can add rest-client.enviornmentVariables in vscode settings.json
## easily switch between environments via command palette (ctrl-shift-P)
## "rest-client.environmentVariables": {
##   "environment-a": {
##     "pc_ip": "10.x.y.z",
##     "basic_auth_token": "<token>",
##      "karbon_cluster_name": "karbon-dev-cluster"
##   },
##   "environment-b": {
##     "pc_ip": "10.a.b.c",
##     "basic_auth_token": "<token>",
##     "karbon_cluster_name": "karbon-qa-cluster"
##   }
## },

@base_url = https://{{pc_ip}}:9440/

# override karbon_cluster_name if not-exisiting in environment configs
@karbon_cluster_name = kalm-demo

### Get Clusters
# @name clusters
GET {{base_url}}/karbon/v1-beta.1/k8s/clusters
Authorization: Basic {{basic_auth_token}}

###
@clusterList = {{clusters.response.body.*.name}}

### Get K8s Versions
# @name k8sversions
GET {{base_url}}/karbon/acs/k8srelease/portal/list
Authorization: Basic {{basic_auth_token}}

### Get Cluster Info
# @name cluster
GET {{base_url}}/karbon/v1/k8s/clusters/{{karbon_cluster_name}}
Authorization: Basic {{basic_auth_token}}

###
@cluster_status = {{cluster.response.body.status}}
@worker_config_node_pool_name = {{cluster.response.body.worker_config.node_pools[0]}}
@etcd_config_node_pool_name = {{cluster.response.body.etcd_config.node_pools[0]}}
@karbon_cluster_uuid = {{cluster.response.body.uuid}}

### Get Compatible K8s Versions
# @name compatible_version
GET {{base_url}}/karbon/acs/k8s/cluster/{{karbon_cluster_uuid}}/k8s_upgrade/versions
Authorization: Basic {{basic_auth_token}}

###
@latest_compatible_version = {{compatible_version.response.body.compatible_versions[0]}}

#### List Registries
# @name registries
GET {{base_url}}/karbon/v1-alpha.1/k8s/clusters/{{karbon_cluster_name}}/registries
Authorization: Basic {{basic_auth_token}}

#### Get Karbon Version
# @name version
GET {{base_url}}/karbon/v1-alpha.1/version
Authorization: Basic {{basic_auth_token}}

#### Get Cluster Worker Node Pool All Configurations
# @name worker_node_pool_config
GET {{base_url}}/karbon/v1-beta.1/k8s/clusters/{{karbon_cluster_name}}/node-pools/{{worker_config_node_pool_name}}
Authorization: Basic {{basic_auth_token}}

###
@workerNodeList = {{worker_node_pool_config.response.body.nodes[*].hostname}}

#### Get Cluster ETCD Node Pool All Configurations
# @name worker_node_pool_config
GET {{base_url}}/karbon/v1-beta.1/k8s/clusters/{{karbon_cluster_name}}/node-pools/{{etcd_config_node_pool_name}}
Authorization: Basic {{basic_auth_token}}

###
@etcdNodeList = {{etcd_config_node_pool_name.response.body.nodes}}



#### Get Cluster Health status
# @name health

GET {{base_url}}/karbon/v1/k8s/clusters/{{karbon_cluster_name}}/health
Authorization: Basic {{basic_auth_token}}
