jenkins_user: admin
jenkins_password: nutanix/4u
argocd_user: admin
argocd_password: nutanix/4u
calm_dsl_user: admin
calm_dsl_pass: nutanix/4u
nutanix_key_user: nutanix
nutanix_user: nutanix
nutanix_password: nutanix/4u
prism_central_user: admin
prism_central_password: nutanix/4u
prism_element_user: admin
prism_element_password: nutanix/4u
windows_domain_user: admin@domain.local
windows_domain_password: nutanix/4u
docker_hub_user: docker-user
docker_hub_password: nutanix/4u