jenkins_user: admin
jenkins_password: <valid_password>
argocd_user: admin
argocd_password: <valid_password>
calm_dsl_user: admin
calm_dsl_pass: <valid_password>
nutanix_key_user: nutanix
nutanix_user: nutanix
nutanix_password: <valid_password>
prism_central_user: admin
prism_central_password: <valid_password>
prism_element_user: admin
prism_element_password: <valid_password>
windows_domain_user: admin@domain.local
windows_domain_password: <valid_password>
docker_hub_user: docker-user
docker_hub_password: <valid_password>